build:
  image: quay.io/darkcrux/docker-client:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - docker build -t drone/demo-webapp:$$COMMIT .
    - docker run -d --name=demo-webapp-$$COMMIT drone/demo-webapp:$$COMMIT
    - docker exec demo-webapp-$$COMMIT sh -c 'bundle exec rake test'
    - docker stop  demo-webapp-$$COMMIT
    - docker rm -f demo-webapp-$$COMMIT
