clone:
  path: github.com/AcalephStorage/demo-webapp
build:
  image: ruby:2.2.4
  command:
    - 'gem update --system'
    - gem install bundler
    - gem install minitest-reporters
    - bundle install
    - bundle exec rake test
