build:
  image: docker:1.8.3
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - docker -H unix:///var/run/docker.sock build -t drone/demo-webapp:$$COMMIT .
    - docker -H unix:///var/run/docker.sock run -d --name=demo-webapp-$$COMMIT drone/demo-webapp:$$COMMIT
    - docker -H unix:///var/run/docker.sock exec demo-webapp-$$COMMIT sh -c 'bundle exec rake test'
    - docker -H unix:///var/run/docker.sock stop  demo-webapp-$$COMMIT
    - docker -H unix:///var/run/docker.sock rm -f demo-webapp-$$COMMIT
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: quay.io/v1
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/acaleph/demo-webapp
    storage_driver: overlay
    file: Dockerfile


