build:
  image: quay.io/darkcrux/docker-client:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    # build image
    - docker build -t drone/demo-webapp:$$COMMIT .
    # test image
    - docker run -d --name=demo-webapp-$$COMMIT drone/demo-webapp:$$COMMIT
    - docker exec demo-webapp-$$COMMIT sh -c 'bundle exec rake test'
    # publish
    - docker login --username=$$DOCKER_USER --password=$$DOCKER_PASSWORD --email=$$DOCKER_EMAIL quay.io
    - docker tag -f drone/demo-webapp:$$COMMIT quay.io/acaleph/demo-webapp:$$COMMIT
    - docker push quay.io/acaleph/demo-webapp:$$COMMIT
    - docker logout quay.io
    # cleanup
    - docker stop  demo-webapp-$$COMMIT
    - docker rm -f demo-webapp-$$COMMIT
    - docker rmi -f quay.io/acaleph/demo-webapp:$$COMMIT
    - docker rmi -f drone/demo-webapp:$$COMMIT

