clone:
  path: github.com/AcalephStorage/demo-webapp
build:
  image: ruby:2.2.4
  commands:
    - 'gem update --system'
    - gem install bundler
    - bundle install
    - bundle exec rake test
publish:
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: robot@fakemail.com
    repo: quay.io/acaleph/demo-webapp
    file: Dockerfile
