debug: true
build:
  image: plugins/drone-docker:latest
  commands:
    - docker build -t drone/demo-webapp .
    - docker run -d --name=demo-webapp drone/demo-webapp
    - docker exec demo-webapp sh -c 'cd /root/demo-webapp && bundle exec rake test'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
