debug: true
clone:
  path: github.com/AcalephStorage/demo-webapp
build:
  image: ruby:2.2.4
  commands:
    - 'gem update --system'
    - gem install bundler
    - bundle install
    - bundle exec rake test
publish:
  docker:
    registry: quay.io/v1
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: acaleph/demo-webapp
    storage_driver: aufs
    file: Dockerfile
