---
apiVersion: v1alpha1
kind: Pipeline
metadata:
  name: demo-webapp
  namespace: acaleph
spec:
  selector:
    matchLabels:
      app: demo-webapp
  template:
    metadata:
      name: demo-webapp
      labels:
        app: demo-webapp
    notif:
      - type: "slack"
        metadata:
          url: slackurl
          channel: slackchannel
          username: slackuser
        secret: acalephnotifier        
    stages:
      - name: Build Image
        type: docker_build
        params:
          dockerfile_path: .
          dockerfile_name: Dockerfile

      - name: Unit Test
        type: command
        params:
          command:
            - rake
            - test

      - name: Deploy Image
        type: docker_publish
        params:
          external_registry: quay.io
          external_image_name: acaleph/demo-webapp
          require_credentials: "TRUE"
          username: user
          password: password
          email: email
        secrets:
          - quayregistrycreds
 
